version: '3.5'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - db_vol:/var/lib/postgresql/data

  guard:
    build: .
    command: bundle exec guard --no-bundler-warning --no-interactions
    depends_on:
      - db
      - selenium_chrome
      - test
    image: mino4qs_guard
    tty: true
    volumes:
      - .:/srv/mino

  selenium_chrome:
    image: selenium/standalone-chrome:3.141.59-titanium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  test:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0' --pid=tmp/pids/test.pid
    depends_on:
      - db
    environment:
      - RAILS_ENV=test
    image: mino4qs_guard
    ports:
      - "3001:3001"
    tty: true
    volumes:
      - .:/srv/mino

  webapp:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' --pid=tmp/pids/development.pid
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    image: mino4qs_webapp
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/srv/mino4qs

volumes:
  db_vol:
    driver: local
