default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  user: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mino4qs_development

test:
  <<: *default
  database: mino4qs_test

production:
  <<: *default
  database: mino4qs_production
  username: mino4qs
  password: <%= ENV['MINO4QS_DATABASE_PASSWORD'] %>
